<?xml  version="1.0"  standalone="yes"?>
<!DOCTYPE help [
<!ELEMENT help (indents | hdr | arg )*>
<!ELEMENT indents EMPTY>
<!ATTLIST indents
  flag CDATA #IMPLIED
  desc CDATA #IMPLIED
  cont CDATA #IMPLIED
  wrap CDATA #IMPLIED>
<!ELEMENT hdr (#PCDATA)>
<!ATTLIST hdr
  vspace CDATA #IMPLIED>
<!ELEMENT arg (desc)>
<!ATTLIST arg
  vspace CDATA #IMPLIED
  flag 	 CDATA #IMPLIED
  opt  	 CDATA #IMPLIED
  repl 	 CDATA #IMPLIED>
<!ELEMENT desc (#PCDATA | p | repl)*>
<!ELEMENT repl (#PCDATA)>
<!ELEMENT p EMPTY>
]>
<help>

  <indents flag="4" desc="8" cont="1" wrap="79"/>

  <hdr vspace="1">Commands are:</hdr>

  <arg flag="-c">
    <desc>
      creates an archive
    </desc>
  </arg>

  <arg flag=" -x">
    <desc>
      extracts files from the archive
    </desc>
  </arg>

  <arg flag="-d">
    <desc>
      compares the archive with the existing filesystem
    </desc>
  </arg>

  <arg flag="-t">
    <desc>
      tests the archive integrity
    </desc>
  </arg>

  <arg flag="-l">
    <desc>
      lists the contents of the archive
    </desc>
  </arg>

  <arg flag="-C">
    <desc>
      isolates the catalogue from an archive
    </desc>
  </arg>

  <arg flag="-+">
    <desc>
       merge two archives / create a sub archive
    </desc>
  </arg>

  <arg vspace="1" flag="-h">
    <desc>
      displays this help information
    </desc>
  </arg>

  <arg flag="-V">
    <desc>
      displays version information
    </desc>
  </arg>

  <indents desc="20"/>

  <hdr vspace="1">Common options:</hdr>

  <arg flag="-v"> <desc> verbose output </desc> </arg>
  <arg flag="-q"> <desc> suppress final statistics report </desc> </arg>
  <arg flag="-vs"> <desc> display skipped files </desc> </arg>

  <arg flag="-R" repl="path">
    <desc>
      filesystem root directory (current dir by default)
    </desc>
  </arg>

  <arg flag="-X" repl=" mask ">
    <desc>
      files to exclude from the operation (none by default)
    </desc>
  </arg>

  <arg flag="-I" repl="mask">
    <desc>
      files to include in the operation (all by default)
    </desc>
  </arg>

  <arg flag="-P" repl="path">
    <desc>
       subdirectory to exclude from the operation
    </desc>
  </arg>

  <arg flag="-g" repl="path">
    <desc>
       subdirectory to include in the operation
    </desc>
  </arg>

  <arg flag="-[" repl="filename">
    <desc>
       filename contains a list of files to include
    </desc>
  </arg>

  <arg flag="-]" repl="path">
    <desc>
       filename contains a list of files to exclude
    </desc>
  </arg>

  <arg flag="-n">
    <desc>
      don't overwrite files
    </desc>
  </arg>

  <arg flag="-w">
    <desc>
       don't warn before overwriting files
    </desc>
  </arg>

  <arg flag="-wa">
    <desc>
       don't warn before overwriting and removing files
    </desc>
  </arg>


  <arg flag="-b">
    <desc>
       ring the terminal bell when user action is required
    </desc>
  </arg>

  <arg flag="-O[ignore-owner | mtime | inode-type]">
    <desc>
       do not consider user and group ownership
    </desc>
  </arg>

  <arg flag="-H" opt="N">
    <desc>
       ignore shift in dates of an exact number of hours
    </desc>
  </arg>

  <arg flag="-E" repl="string">
    <desc>
       command to execute between slices
    </desc>
  </arg>

  <arg flag="-F" repl="string">
    <desc>
       same as -E but for the archive of reference
    </desc>
  </arg>

  <arg flag="-u" repl="mask">
    <desc>
      mask to ignore certain EA
    </desc>
  </arg>

  <arg flag="-U" repl="mask">
    <desc>
      mask to allow certain EA
    </desc>
  </arg>

  <arg flag="-K" repl="string">
    <desc>
       use <repl>string</repl> as key to encrypt/decrypt
    </desc>
  </arg>

  <arg flag="-J" repl="string">
    <desc>
       same as -K but it does concern the archive of reference
    </desc>
  </arg>

 <arg flag="-#" repl="integer">
    <desc>
       encryption block size
    </desc>
  </arg>

 <arg flag="-*" repl="integer">
    <desc>
       same as -# but for archive of reference
    </desc>
  </arg>


  <arg flag="-B" repl="filename">
    <desc>
       read options from given file
    </desc>
  </arg>

  <arg flag="-N">
    <desc>
        do not read ~/.darrc nor /etc/darrc configuration file
    </desc>
  </arg>

  <arg flag="-e">
    <desc>
       dry run, fake execution, nothing is produced
    </desc>
  </arg>

  <arg flag="-Q">
    <desc>
      suppress the initial warning when not launched from a tty
    </desc>
  </arg>

  <arg flag="-aa">
    <desc>
       do not try to preserve atime of file open for reading.
    </desc>
  </arg>

  <arg flag="-ac">
    <desc>
       do not try to preserve ctime (default behavior).
    </desc>
  </arg>

  <arg flag="-am">
    <desc>
       set ordered mode for all filters
    </desc>
  </arg>

  <arg flag="-an">
    <desc>
      the masks that follow are now case insensitive
    </desc>
  </arg>

  <arg flag="-acase">
    <desc>
      the masks that follow are now case sensitive
    </desc>
  </arg>

  <arg flag="-ar">
    <desc>
       set the following masks to be regex expressions
    </desc>
  </arg>

  <arg flag="-ag">
    <desc>
      set the following masks to be glob expressions
    </desc>
  </arg>

  <arg flag="-j">
    <desc>
        ask user what to do when memory is exhausted
    </desc>
  </arg>

  <hdr vspace="1">
    Saving / Isolation / merging options (to use with -c, -C or -+):
  </hdr>

  <arg flag="-A" opt="path/" repl="basename">
    <desc>
        archive to take as reference
    </desc>
  </arg>

  <arg flag="-@" opt="path/" repl="basename">
    <desc>
        auxiliary archive of reference for merging
    </desc>
  </arg>

  <arg flag="-$" repl="string">
    <desc>
       encryption key for auxiliary archive
    </desc>
  </arg>

  <arg flag="-~" repl="string">
    <desc>
        command between slices of the auxiliary archive
    </desc>
  </arg>

  <arg flag="-z" opt="level">
    <desc>
      compress data in archive using gzip algorithm
    </desc>
  </arg>

  <arg flag="-z" opt="bzip2[:level]">
    <desc>
      compress data in archive using bzip2 algorithm.
    </desc>
  </arg>

  <arg flag="-s" repl="integer">
    <desc>
      split the archive in several files of size <repl>integer</repl>
    </desc>
  </arg>

  <arg flag="-S" repl="integer">
    <desc>
      first file size (if different from following ones)
    </desc>
  </arg>

  <arg flag="-aSI">
    <desc>
      slice size suffixes k, M, T, G, etc. are power of 10
    </desc>
  </arg>

  <arg flag="-abinary">
    <desc>
      slice size suffixes k, M, T, G, etc. are power of 2
    </desc>
  </arg>

  <arg flag="-p">
    <desc>
      pauses before writing to a new file
    </desc>
  </arg>

  <arg flag="-D">
    <desc>
      excluded directories are stored as empty directories
    </desc>
  </arg>

  <arg flag="-Z" repl="mask">
    <desc>
      do not compress the matching filenames
    </desc>
  </arg>

  <arg flag="-Y" repl="mask">
    <desc>
       do only compress the matching filenames
    </desc>
  </arg>

  <arg flag="-m" repl="number">
    <desc>
       do not compress file smaller than <repl>number</repl>
    </desc>
  </arg>

  <arg flag="--nodump">
    <desc>
    do not backup, files having the nodump 'd' flag set
    </desc>
  </arg>

  <arg flag="-@" opt="path/" repl="basename">
    <desc>
       Do on-fly catalogue isolation of the resulting archive
    </desc>
  </arg>

  <arg flag="-M">
    <desc>
      stay in the same filesystem while scanning directories
    </desc>
  </arg>

  <arg flag="-,">
    <desc>
       ignore directories that follow the Directory Tagging Standard
    </desc>
  </arg>

  <arg flag="-/" repl="string">
    <desc>
        which way dar can overwrite files at archive merging or extraction time
    </desc>
  </arg>

  <arg flag="-^" repl="string">
    <desc>
       permission[:user[:group]] of created slices
    </desc>
  </arg>

  <hdr vspace="1">
  Restoring options (to use with -x) :
  </hdr>

  <arg flag="-k">
    <desc>
      do not remove files destroyed since the reference backup
    </desc>
  </arg>

  <arg flag="-r">
    <desc>
      do not restore file older than those on filesystem
    </desc>
  </arg>

  <arg flag="-f">
    <desc>
      do not restore directory structure
    </desc>
  </arg>

  <hdr vspace="1">
    Reading options (to use with -x, -d, -t, -l, -A)
  </hdr>

  <arg flag="-i" repl="named pipe">
    <desc>
      pipe to use instead of std input to read data from dar_slave
    </desc>
  </arg>

  <arg flag="-o" repl="named pipe">
    <desc>
      pipe to use instead of std output to orders dar_slave
    </desc>
  </arg>

  <hdr vspace="1">
    Listing options (to use with -l):
  </hdr>

  <arg flag="-T">
    <desc>
        tree output format
    </desc>
  </arg>

  <arg flag="-as">
    <desc>
        only list files saved in the archive
    </desc>
  </arg>

  <hdr vspace="2">
    Type \"man dar\" for more details and for all available options.
  </hdr>

<!--
$Id: dar.xml,v 1.27 2011/01/22 19:07:42 edrusb Rel $

Revision 1.3  2002/08/20 13:44:08  cs1cwm
Added DTD and removed the #ifdef and #endif.

It now passes xmllint validation.

Revision 1.2  2002/08/17 13:41:48  cs1cwm
Changed to use arg flag, opt and repl attributes.

Some changes to text.

Revision 1.1  2002/08/17 13:13:31  cs1cwm
Initial revision

-->
</help>
