<?xml  version="1.0"  standalone="yes"?>
<!DOCTYPE help [
<!ELEMENT help (indents | hdr | arg )*>
<!ELEMENT indents EMPTY>
<!ATTLIST indents
  flag CDATA #IMPLIED
  desc CDATA #IMPLIED
  cont CDATA #IMPLIED
  wrap CDATA #IMPLIED>
<!ELEMENT hdr (#PCDATA)>
<!ATTLIST hdr
  vspace CDATA #IMPLIED>
<!ELEMENT arg (desc)>
<!ATTLIST arg 
  vspace CDATA #IMPLIED
  flag 	 CDATA #IMPLIED
  opt  	 CDATA #IMPLIED
  repl 	 CDATA #IMPLIED>
<!ELEMENT desc (#PCDATA | p | repl)*>
<!ELEMENT repl (#PCDATA)>
<!ELEMENT p EMPTY>
]>
<help>

  <indents flag="4" desc="20" cont="1" wrap="79"/>

  <arg vspace="1" flag=" ">
    <desc>
        the first non options argument is the name of the archive to read while the
	second non option argument is the name of the new archive to create. Both are mandatory.
    </desc>
  </arg>

  <hdr vspace="1">options:</hdr>

  <arg flag="-h">
    <desc>
      displays this help information
    </desc>
  </arg>

  <arg flag="-V">
    <desc>
      displays version information
    </desc>
  </arg>

  <arg flag="-s" repl="integer">
    <desc>
      split the archive in several files of size <repl>integer</repl>
    </desc>
  </arg>

  <arg flag="-S" repl="integer">
    <desc>
      first file size (if different from following ones) -- requires -s
    </desc>
  </arg>

  <arg flag="-p">
    <desc>
      pauses before writing to a new file -- requires -s
    </desc>
  </arg>

  <arg flag="-n">
    <desc>
      don't overwrite files
    </desc>
  </arg>

  <arg flag="-w">
    <desc>
       don't warn before overwriting files
       <p/> 
       by default overwriting is allowed but a warning is issued first
    </desc>
  </arg>

  <arg flag="-b">
    <desc>
       ring the terminal bell when user action is required
    </desc>
  </arg>

  <arg flag="-E" repl="string">
    <desc>
       command line to execute between slices of destination archive
    </desc>
  </arg>

  <arg flag="-F" repl="string">
    <desc>
       command line to execute between slice of source archive
    </desc>
  </arg>

  <hdr vspace="1">
    See man page for more details.
  </hdr>
<!--
$Id: dar_xform.xml,v 1.4 2003/02/07 07:10:25 edrusb Stab $

Revision 1.3  2002/08/20 13:44:08  cs1cwm
Added DTD and removed the #ifdef and #endif.

It now passes xmllint validation.

Revision 1.2  2002/08/17 13:41:48  cs1cwm
Changed to use arg flag, opt and repl attributes.

Some changes to text.

Revision 1.1  2002/08/17 13:13:31  cs1cwm
Initial revision

-->
</help>
